runtime: nodejs16

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /favicon.ico
    static_files: build/favicon.ico
    upload: build/favicon.ico


  - url: /
    static_dir: build


